# Copyright 2019 HAProxy Technologies LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: kubernetes-ingress
description: A Helm chart for HAProxy Kubernetes Ingress Controller
type: application
version: 1.44.0
appVersion: 3.1.0-rc1
kubeVersion: ">=1.23.0-0"
keywords:
  - ingress
  - haproxy
home: https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress
sources:
  - https://github.com/haproxytech/kubernetes-ingress
icon: https://raw.githubusercontent.com/haproxytech/helm-charts/main/kubernetes-ingress/chart-icon.png
maintainers:
  - name: Dinko Korunic
    email: dkorunic@haproxy.com
engine: gotpl
annotations:
  artifacthub.io/changes: |
    - Support PodMonitor as alternative to ServiceMonitor (#271)
    - Use correct values for PodMonitor test (#272)
    - Support to specify HPA behavior (#274)
    - Make controller.podAnnotations templatable (#276)
    - Fix controller.podAnnotations not being templatable in every location (#277)
    - Make controller.config templatable (#279)
