controller:
  ingressClass: 'hono-non-http-ingress'
  image:
    allowPrivilegeEscalation: false
  ingressClassResource:
    name: 'hono-non-http-ingress'
    controllerValue: "k8s.io/hono-non-http-ingress"
    enabled: true
  replicaCount: 1
  nodeSelector:
    node-role.kubernetes.io/infra: "true"
  service:
    enableHttp: false
    enableHttps: false
    loadBalancerIP: "34.100.160.104"  # Replace with the reserved IP
    annotations:
      networking.gke.io/load-balancer-type: "External"  # Optional for external LB
  extraArgs:
    v: "4"

tcp:
    5671: "hono/hono-adapter-amqp:5671"
    8883: "hono/hono-adapter-mqtt:8883"
    28443: "hono/hono-service-device-registry-ext:28443"
    9092:  "hono/ikafka:9092"
    1883: "irabbitmq/irabbitmq:1883"
    1884: "technique/irabbitmq-techniquedev:1883"