steps:
  # Step 1: Deploy using Cloud Deploy and specify Skaffold file
  - id: "Authentication With GKE"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials $_CLUSTER_NAME --region $_REGION


  # - id: Deployment of nginx-ingress-dev
  #   name: gcr.io/k8s-skaffold/skaffold
  #   entrypoint: skaffold
  #   args:
  #     - "deploy"
  #     - "--filename=skaffold-nginx-dev-ingress.yaml"
  #     - "--force"

  - id: Deployment of data-ingress-dev
    name: gcr.io/k8s-skaffold/skaffold
    entrypoint: skaffold
    args:
      - "deploy"
      - "--filename=skaffold-data-ingress.yaml"
      - "--force"

  - id: Deployment of public-ingress-dev
    name: gcr.io/k8s-skaffold/skaffold
    entrypoint: skaffold
    args:
      - "deploy"
      - "--filename=skaffold-public-dev-ingress.yaml"
      - "--force"

substitutions:
  _RELEASE_NAME: nginx-dev-ingress
  _CLUSTER_NAME: "iplon-dev"
  _REGION: "asia-south1-a"

logsBucket: 'gs://iplon-storage-logs-data/codebuildlogs'

options:
  logging: GCS_ONLY