steps:
  # Step 1: Deploy using Cloud Deploy and specify Skaffold file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials $_CLUSTER_NAME --region $_REGION

  - name: gcr.io/k8s-skaffold/skaffold
    args:
      - "deploy"
      - "--force"
    # entrypoint: gcloud
    # args:
    #   - 'deploy'
    #   - 'releases'
    #   - 'create'
    #   - '${_RELEASE_NAME}-${SHORT_SHA}'
    #   - '--delivery-pipeline=dev-ingress-controller'
    #   - '--region=us-west2'
    #   - '--skaffold-file=skaffold-nginx-dev-ingress.yaml'


substitutions:
  _RELEASE_NAME: nginx-dev-ingress
  _CLUSTER_NAME: "iplon-dev"
  _REGION: "ap-south1-a"

logsBucket: 'gs://iplon-storage-logs-data/codebuildlogs'

options:
  logging: GCS_ONLY