apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: public-ingress-dev
deploy:
  helm:
    releases:
      - name: public-ingress-dev
        namespace: ingress
        chartPath: ./kubernetes-ingress-ha-proxy-dev
        valuesFiles:
          - ./kubernetes-ingress-ha-proxy-dev/values-public-ingress-dev.yaml
        version: 4.12.0
        recreatePods: true