apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: nginx-dev-ingress
deploy:
  helm:
    releases:
      - name: nginx-dev-ingress
        namespace: ingress
        chartPath: ./ingress-nginx-dev
        valuesFiles:
          - ./ingress-nginx-dev/values-nginx-dev-ingress.yaml
        version: 4.12.0
        recreatePods: true