apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: data-ingress
deploy:
  helm:
    releases:
      - name: data-ingress
        namespace: ingress
        chartPath: ./ingress-nginx
        valuesFiles:
          - ./ingress-nginx/values-data-ingress.yaml
        version: 4.12.0
        recreatePods: true