apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: indoatlantic-ingress
deploy:
  helm:
    releases:
      - name: indoatlantic-ingress
        namespace: ingress
        chartPath: ./ingress-nginx-prod
        valuesFiles:
          - ./ingress-nginx-prod/values-indoatlantic-ingress.yaml
        version: 4.12.0
        recreatePods: true