apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-prod-ingress
  namespace: iplonapis
  labels:
     name: api-prod
     reponame: iplon-ingress

  annotations:
    # kubernetes.io/ingress.class: "tr-api-ingress-prod"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod-api-ingress"
    kubernetes.io/ingress.class: "public-ingress"
    cert-manager.io/cluster-issuer: "letsencrypt-public-ingress"
    kubernetes.io/force-ssl-redirect: 'true'
    kubernetes.io/ingress.allow-http: "false"
    # traefik.ingress.kubernetes.io/router.middlewares: iplonapis-sunalpha@kubernetescrd , iplonapis-regexapi@kubernetescrd


spec:

  tls:
    - hosts:
      - api-int.iplon.co.in
      secretName: sunalpha-tls-prod


  rules:
  - host: api-int.iplon.co.in
    http:
        paths:
          - path: /api-docs/chithoor-UI
            pathType: Prefix
            backend:
              service:
                name: sunalpha-chitthoor-svc
                port:
                  number: 80
  - host: api-int.iplon.co.in
    http:
        paths:
          - path: /chithoor/
            pathType: Prefix
            backend:
              service:
                name: sunalpha-chitthoor-svc
                port:
                  number: 80
  - host: api-int.iplon.co.in
    http:
        paths:
          - path: /api-docs/sunalpha-UI
            pathType: Prefix
            backend:
              service:
                name: sunalpha-all-svc
                port:
                  number: 80

  - host: api-int.iplon.co.in
    http:
        paths:
          - path: /sunalpha/
            pathType: Prefix
            backend:
              service:
                name: sunalpha-all-svc
                port:
                  number: 80
  - host: api-int.iplon.co.in
    http:
        paths:
          - path: /fleet/
            pathType: Prefix
            backend:
              service:
                name: api-docs-fleet-svc
                port:
                  number: 80
  - host: api-int.iplon.co.in
    http:
        paths:
          - path: /api-docs/fleet/
            pathType: Prefix
            backend:
              service:
                name: api-docs-fleet-svc
                port:
                  number: 80

  - host: api-int.iplon.co.in
    http:
        paths:
          - path: /plant/
            pathType: Prefix
            backend:
              service:
                name: api-docs-plant-svc
                port:
                  number: 80
  - host: api-int.iplon.co.in
    http:
        paths:
          - path: /api-docs/plant/
            pathType: Prefix
            backend:
              service:
                name: api-docs-plant-svc
                port:
                  number: 80

  - host: api-int.iplon.co.in
    http:
        paths:
          - path: /Access_Token/
            pathType: Prefix
            backend:
              service:
                name: api-docs-plant-svc
                port:
                  number: 80
