apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcs-storage-class-influx-iplasia
provisioner: gcsfuse.csi.storage.gke.io
parameters:
  # Replace with your bucket name
  projectID: iplon-india
  bucket: influx-iplasia
  # Optional: Set filesystem type (ext4 is default)
  # filesystemType: ext4