controller:
  ingressClass: 'imqtt-ingress'
  image:
    allowPrivilegeEscalation: false
  ingressClassResource:
    name: 'imqtt-ingress'
    controllerValue: "k8s.io/imqtt-ingress"
    enabled: true
  replicaCount: 1
  nodeSelector:
    node-role.kubernetes.io/infra: "true"
  service:
    enableHttp: false
    enableHttps: false
    loadBalancerIP: "35.200.172.163"  # Replace with the reserved IP
    annotations:
      networking.gke.io/load-balancer-type: "External"  # Optional for external LB
  extraArgs:
    v: "4"
tcp:
    1883: "irabbitmq/irabbitmq:1883"