controller:
  ingressClass: 'indopacific-ingress'
  image:
    allowPrivilegeEscalation: false
  ingressClassResource:
    name: 'indopacific-ingress'
    controllerValue: "k8s.io/indopacific-ingress"
    enabled: true
  replicaCount: 1

  nodeSelector:
    node-role.kubernetes.io/infra: "true"