controller:
  ingressClass: 'data-ingress'
  image:
    allowPrivilegeEscalation: false
  ingressClassResource:
    name: 'data-ingress'
    controllerValue: "k8s.io/data-ingress"
    enabled: true
  replicaCount: 1
  nodeSelector:
    node-role.kubernetes.io/infra: "true"
  service:
    loadBalancerIP: "34.47.152.30"  # Replace with the reserved IP
    annotations:
      networking.gke.io/load-balancer-type: "External"  # Optional for external LB
  extraArgs:
    v: "4"