
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-public-api-gateway
spec:
  acme:
   # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
    email: software.vcontrol@iplon.co.in
       # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: cert-manager-public-api-gateway
       # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudDNS:
          project: iplon-india
          serviceAccountSecretRef:
            name: clouddns-dns01-solvet-svc-act
            key: key.json