apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pts-cert
  namespace: default
spec:
  secretName: pts-cert-secret  # Secret where the certificate will be stored
  issuerRef:
    name: letsencrypt-pvindia-pts-ingress
    kind: ClusterIssuer
  commonName: pvindia-pts.iplon.co.in  # Service name
  dnsNames:
  - pvindia-pts.iplon.co.in